"""Build the self-contained submission: one file, one solve(), no repo imports.

The readable source stays split across period_router/; this stitches it (and
the team's solver/cost.py, which it uses for scoring) into a single file that
needs only the standard library and networkx.

Run from the Computational Track folder:
    python -m uv run python -m period_router.bundle
It rewrites submission.py and the notebook's submission cell (cell 20).
"""

import json
import re
from pathlib import Path

TRACK = Path(__file__).resolve().parents[1]
PACKAGE = TRACK / "period_router"
SOURCES = [TRACK / "solver" / "cost.py"] + [
    PACKAGE / f"{name}.py"
    for name in ("chip", "program", "layout", "seating", "fit", "token_swap", "lookahead", "initial", "periods", "solve")
]
INTERNAL_IMPORT = re.compile(r"^from (\.\w*|solver\.cost) import ")
EXTERNAL_IMPORT = re.compile(r"^(import \w|from \w[\w.]* import )")

HEADER = '''"""QSITE 2026 Computational Track: submission.

Self-contained: needs only the Python standard library and networkx.
GENERATED by `python -m period_router.bundle` from the period_router/ package
and solver/cost.py. Edit those, then rebuild; don't edit this file by hand.

Method: cut the program into periods that fit the chip with zero SWAPs; for
each, reshuffle to the closest seating that fits (looking ahead to the next
gates) or route it gate by gate, whichever scores better; try two starting
seatings, refine each with the forward-backward trick, keep the best.
"""

from __future__ import annotations
'''

NOTEBOOK_CELL_ID = "f8cdd038"  # starter.ipynb cell 20, the submission cell
NOTEBOOK_SCORING = '''

# Score every benchmark next to the baseline.
baseline_total = our_total = 0.0
for name, program in BENCHMARKS.items():
    bl_pl, bl_rt = baseline_solve(program, GRAPH)
    baseline = score_summary(program, GRAPH, bl_pl, bl_rt)
    placement, routed = solve(program, GRAPH)
    result = score_summary(program, GRAPH, placement, routed)
    if not result["valid"]:
        raise AssertionError(f"{name}: {result['message']}")
    baseline_total += baseline["score"]
    our_total += result["score"]
    print(f"{name:16s} baseline {baseline['score']:6.1f}   ours {result['score']:6.1f}"
          f"   ({result['swap_count']} swaps, depth {result['depth']})")
print(f"{'TOTAL':16s} baseline {baseline_total:6.1f}   ours {our_total:6.1f}")
'''


def merge_imports(lines: list[str]) -> list[str]:
    """One line per module: 'from x import a' + 'from x import b' -> 'from x import a, b'."""
    plain: set[str] = set()
    names_from: dict[str, set[str]] = {}
    for line in lines:
        if line.startswith("from "):
            module, _, names = line[len("from "):].partition(" import ")
            names_from.setdefault(module, set()).update(n.strip() for n in names.split(","))
        else:
            plain.add(line)
    merged = list(plain) + [f"from {m} import {', '.join(sorted(n))}" for m, n in names_from.items()]
    return sorted(merged, key=lambda line: line.split()[1])


def build_source() -> str:
    imports: list[str] = []
    bodies: list[str] = []
    for path in SOURCES:
        body = []
        for line in path.read_text(encoding="utf-8").splitlines():
            if "import (" in line:
                raise ValueError(f"{path.name}: multi-line imports are not supported by the bundler")
            if INTERNAL_IMPORT.match(line):
                continue  # everything it names is defined earlier in the bundle
            if EXTERNAL_IMPORT.match(line):
                imports.append(line)
                continue
            body.append(line)
        text = "\n".join(body).strip("\n")
        bodies.append(f"# {'-' * 70}\n# {path.relative_to(TRACK).as_posix()}\n# {'-' * 70}\n\n{text}\n")
    merged = merge_imports(imports)
    stdlib = [i for i in merged if "networkx" not in i]
    third_party = [i for i in merged if "networkx" in i]
    return HEADER + "\n" + "\n".join(stdlib) + "\n\n" + "\n".join(third_party) + "\n\n\n" + "\n\n\n".join(bodies)


def write_submission(source: str) -> Path:
    out = TRACK / "submission.py"
    out.write_text(source, encoding="utf-8")
    return out


def write_notebook_cell(source: str) -> Path:
    path = TRACK / "starter.ipynb"
    notebook = json.loads(path.read_text(encoding="utf-8"))
    cell = next(c for c in notebook["cells"] if c.get("id") == NOTEBOOK_CELL_ID)
    cell["source"] = (source + NOTEBOOK_SCORING).splitlines(keepends=True)
    cell["outputs"] = []
    cell["execution_count"] = None
    # indent=1 + ensure_ascii=False is how Jupyter saves, so other cells stay byte-identical
    path.write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


if __name__ == "__main__":
    source = build_source()
    print(f"wrote {write_submission(source).name} ({len(source.splitlines())} lines)")
    print(f"wrote {write_notebook_cell(source).name} (submission cell)")
