"""Rebuild a valid submission.zip without opening the notebook.

Does exactly what the notebook's Part 4 cells do, in one command:

    python3 dev/build.py                  # build, validate, smoke test
    python3 dev/build.py --no-smoke       # build + static validation only (fast)
    python3 dev/build.py --cases local zz conjugated mixed --seeds 41 73

It packages `main.py` plus the two attack templates, then re-runs the SAME
validator the server uses on the resulting bytes, then executes the archive
against public practice attacks in fresh Python processes.

Exit code 0 means the archive is valid for upload. Nonzero means do not upload.

Note what the checks do and do not mean:
  * STATIC_VALIDATED  -- archive structure, entrypoint signature, rules hash and
                         both attack templates pass. Nothing was executed.
  * VALIDATED_LOCALLY -- the above, plus the packaged code ran to completion on
                         the selected public cases.
Neither is a claim about recovery quality. A valid program can score zero.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DEV_DIR = Path(__file__).resolve().parent
IONQ_DIR = DEV_DIR.parent


def _ensure_sdk():
    for base in (DEV_DIR, *DEV_DIR.parents):
        candidate = base / "_quantum_duel_sdk_0_7_2"
        if candidate.is_dir():
            if str(candidate) not in sys.path:
                sys.path.insert(0, str(candidate))
            return candidate
    raise SystemExit(
        "Could not find _quantum_duel_sdk_0_7_2. It is generated by the notebook's\n"
        "Setup cell; run that once, then this script works standalone."
    )


_ensure_sdk()

from qduel_sdk.rules import Rules  # noqa: E402
from qduel_sdk.contracts import Template  # noqa: E402
from qduel_sdk.submission import build_submission, validate_solution  # noqa: E402

# Cup 1 default. Change with --profile for the eight-qubit rounds.
from qduel_sdk.profiles import profile_rules  # noqa: E402


def workspace(rules):
    return IONQ_DIR / "quantum_duel_work" / rules.version


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--profile", default=None,
                        help="ruleset id; default is the four-qubit playtest profile")
    parser.add_argument("--version", default="v1",
                        help="entry version label recorded inside submission.json")
    parser.add_argument("--files", nargs="+", default=["main.py"],
                        help="source files to package; list EVERY helper main.py imports")
    parser.add_argument("--cases", nargs="+", default=["local", "zz", "conjugated", "mixed"],
                        help="public practice cases for the smoke test")
    parser.add_argument("--seeds", type=int, nargs="+", default=[41],
                        help="draw seeds for the smoke test")
    parser.add_argument("--timeout", type=int, default=180,
                        help="per-case smoke timeout in seconds (local safety setting)")
    parser.add_argument("--no-smoke", action="store_true",
                        help="skip execution; static validation only")
    args = parser.parse_args(argv)

    rules = Rules() if args.profile is None else profile_rules(args.profile)
    root = workspace(rules)
    source = root / "my_solution"
    attacks_file = root / "attacks.json"
    output = root / "submission.zip"

    if not source.is_dir():
        raise SystemExit(f"No solution directory at {source}")
    missing = [f for f in args.files if not (source / f).is_file()]
    if missing:
        raise SystemExit(f"Missing source file(s) in {source}: {', '.join(missing)}")
    if not attacks_file.is_file():
        raise SystemExit(f"No attacks.json at {attacks_file}")

    raw = json.loads(attacks_file.read_text(encoding="utf-8"))
    if not isinstance(raw, list) or len(raw) != 2:
        raise SystemExit("attacks.json must contain exactly two attack templates")
    attacks = [Template.model_validate(t) for t in raw]

    print(f"ruleset  : {rules.version} ({rules.qubits} qubits, {rules.total_shots} shots)")
    print(f"source   : {source}")
    print(f"packaging: {', '.join(args.files)}")
    for t in attacks:
        ent = sum(1 for g in t.gates if len(g.targets) == 2)
        print(f"attack   : {t.name!r}  {len(t.gates)} gates, {ent} entanglers")
    print()

    # build_submission itself re-validates the bytes it just wrote, including
    # running the attack qualifier, so a bad template fails here.
    print("building ...")
    build_submission(source, attacks, output, version=args.version,
                     rules=rules, files=tuple(args.files))

    print("validating ...")
    report = validate_solution(output, rules=rules, run_smoke=not args.no_smoke,
                               trusted_code=not args.no_smoke,
                               cases=tuple(args.cases), seeds=tuple(args.seeds),
                               timeout=args.timeout)

    print()
    print(f"status           : {report['status']}")
    print(f"valid_for_upload : {report['valid_for_upload']}")
    print(f"sha256           : {report['sha256']}")
    archive = report.get("archive", {})
    print(f"size             : {archive.get('bytes')} bytes zipped, "
          f"{archive.get('expanded_bytes')} expanded")
    for member in archive.get("files", []):
        print(f"  member         : {member['name']:<18}{member['bytes']:>7} B  "
              f"{member['sha256'][:16]}")
    check = report.get("attack_check", {})
    if check:
        print(f"attack_check     : {check.get('status')} "
              f"({check.get('family_distinctness', '')[:60]}...)")

    if report["status"] == "INVALID":
        for err in report.get("errors", []):
            print(f"  ERROR: {err}")
        return 1

    smoke = report.get("smoke")
    if smoke:
        print()
        print(f"{'case':<14}{'seed':>6}{'status':>10}{'points':>9}")
        print("-" * 41)
        for row in smoke["cases"]:
            pts = row.get("recovery_points")
            pts = f"{pts:.2f}" if isinstance(pts, (int, float)) else "-"
            print(f"{row.get('case',''):<14}{row.get('seed',''):>6}"
                  f"{row.get('status',''):>10}{pts:>9}")
            if row.get("status") != "PASSED":
                print(f"    {row.get('error','')[:100]}")
        print("-" * 41)
        print("PASSED means the program completed, not that it recovers well.")

    print()
    print(f"archive: {output}")
    evidence = root / "local_validation_report.json"
    evidence.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
    print(f"report : {evidence}")

    return 0 if report["valid_for_upload"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
