"""QSITE 2026 Computational Track: submission.

Self-contained: needs only the Python standard library and networkx.
GENERATED by `python -m period_router.bundle` from the period_router/ package
and solver/cost.py. Edit those, then rebuild; don't edit this file by hand.

Method: cut the program into periods that fit the chip with zero SWAPs; for
each, reshuffle to the closest seating that fits (looking ahead to the next
gates) or route it gate by gate, whichever scores better; try two starting
seatings, refine each with the forward-backward trick, keep the best.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass
import math

import networkx as nx


# ----------------------------------------------------------------------
# solver/cost.py
# ----------------------------------------------------------------------

def used_logical_qubits(program):
    """returns list of used logical notebooks in order to iterate through"""
    qubits = set()
    for g in program:
        for q in g[1:]:
            qubits.add(q)

    return sorted(qubits)

def depth(routed_program):
    """returns depth"""
    counts = dict.fromkeys(used_logical_qubits(routed_program), 0)

    for g in routed_program:
        if g[0] != '1Q':
            max_val = max(counts[g[1]], counts[g[2]])
            counts[g[1]] = max_val + 1
            counts[g[2]] = max_val + 1

    return max(counts.values()) if counts else 0

def cost(routed_program):
    """returns cost of routed program"""
    swaps = 0
    for g in routed_program:
        if g[0] == 'SWAP':
            swaps += 1
    return swaps + 0.5*depth(routed_program)

def validate(program, graph, placement, routed_program):
    """checks if placed routed program on hardware is equal to original"""
    # placement must cover exactly the logical qubits the program uses
    if set(placement.keys()) != set(used_logical_qubits(program)):
        return False
    # no two logical qubits mapped to physical qubit
    if len(set(placement.values())) != len(placement):
        return False
    # every phys has to actually exist on the hardware
    if not set(placement.values()).issubset(graph.nodes):
        return False

    # how physical qubits map to logical qubits
    phys_to_log = {v:k for k,v in placement.items()}
    decompiled = []
    for g in routed_program:
        if g[0] == 'SWAP':
            if not graph.has_edge(g[1], g[2]):
                return False
            left = phys_to_log.pop(g[1], None)
            right = phys_to_log.pop(g[2], None)
            if right is not None:
                phys_to_log[g[1]] = right
            if left is not None:
                phys_to_log[g[2]] = left
        elif g[0] == '2Q':
            if not graph.has_edge(g[1], g[2]):
                return False
            if g[1] not in phys_to_log or g[2] not in phys_to_log:
                return False
            decompiled.append(('2Q', phys_to_log[g[1]], phys_to_log[g[2]]))
        elif g[0] == '1Q':
            if g[1] not in phys_to_log:
                return False
            decompiled.append(('1Q', phys_to_log[g[1]]))
        else:
            return False

    return decompiled == program



# ----------------------------------------------------------------------
# period_router/chip.py
# ----------------------------------------------------------------------

"""Facts about the hardware graph, computed once per solve() call.

Everything the router needs to know about the chip is derived here from the
graph it is given, so nothing in the package is specific to the 20-qubit chip.
"""




@dataclass
class Chip:
    graph: nx.Graph
    dist: dict  # dist[p][q] = number of hops between physical qubits p and q
    max_degree: int  # most neighbours any physical qubit has
    girth: float  # length of the shortest loop (inf if the graph has none)
    bipartite: bool  # True if every loop has even length
    center: int  # physical qubit closest to everything; used to seed placement
    neighbors: dict  # neighbors[p] = frozenset of p's neighbours (plain dict: fast in hot loops)


def make_chip(graph: nx.Graph) -> Chip:
    if not nx.is_connected(graph):
        raise ValueError("hardware graph must be connected")
    dist = dict(nx.all_pairs_shortest_path_length(graph))
    return Chip(
        graph=graph,
        neighbors={p: frozenset(graph.neighbors(p)) for p in graph.nodes},
        dist=dist,
        max_degree=max(degree for _, degree in graph.degree()),
        girth=nx.girth(graph),
        bipartite=nx.is_bipartite(graph),
        center=min(graph.nodes, key=lambda p: (max(dist[p].values()), -graph.degree(p), p)),
    )



# ----------------------------------------------------------------------
# period_router/program.py
# ----------------------------------------------------------------------

"""Helpers for reading a program: which qubits it uses and who talks to whom."""




def logical_qubits(program: list[tuple]) -> list[int]:
    """Every logical qubit the program mentions, sorted. Labels can have gaps."""
    return sorted({qubit for op in program for qubit in op[1:]})


def first_appearance(program: list[tuple]) -> list[int]:
    """Logical qubits in the order they first appear in the program."""
    seen: dict[int, None] = {}
    for op in program:
        for qubit in op[1:]:
            seen.setdefault(qubit, None)
    return list(seen)


def interaction_graph(ops: list[tuple]) -> nx.Graph:
    """One node per logical qubit in a 2Q gate, one edge per pair that interacts."""
    graph = nx.Graph()
    for op in ops:
        if op[0] == "2Q":
            graph.add_edge(op[1], op[2])
    return graph


def upcoming_pairs(program: list[tuple], start: int, limit: int, decay: float) -> list[tuple[int, int, float]]:
    """The first `limit` 2Q gates from program[start:] as (a, b, weight),
    weights 1, decay, decay**2, ... so nearer gates count more."""
    pairs = []
    weight = 1.0
    for op in program[start:]:
        if len(pairs) == limit:
            break
        if op[0] == "2Q":
            pairs.append((op[1], op[2], weight))
            weight *= decay
    return pairs


def partner_counts(program: list[tuple]) -> dict[int, Counter]:
    """partner_counts(program)[a][b] = how many 2Q gates act on the pair a, b."""
    counts: dict[int, Counter] = defaultdict(Counter)
    for op in program:
        if op[0] == "2Q":
            counts[op[1]][op[2]] += 1
            counts[op[2]][op[1]] += 1
    return counts



# ----------------------------------------------------------------------
# period_router/layout.py
# ----------------------------------------------------------------------

"""Who sits where, kept in both directions and updated on every SWAP."""


class Layout:
    def __init__(self, placement: dict[int, int]):
        self.where = dict(placement)  # logical -> physical
        self.occupant = {physical: logical for logical, physical in placement.items()}  # physical -> logical

    def copy(self) -> "Layout":
        return Layout(self.where)

    def swap(self, p: int, q: int) -> None:
        """Exchange whatever sits on physical qubits p and q (either may be empty)."""
        a = self.occupant.pop(p, None)
        b = self.occupant.pop(q, None)
        if a is not None:
            self.occupant[q] = a
            self.where[a] = q
        if b is not None:
            self.occupant[p] = b
            self.where[b] = p

    def emit(self, op: tuple) -> tuple:
        """Rewrite a program op onto physical qubits, keeping the operand order."""
        if op[0] == "2Q":
            return ("2Q", self.where[op[1]], self.where[op[2]])
        if op[0] == "1Q":
            return ("1Q", self.where[op[1]])
        raise ValueError(f"unknown op kind: {op[0]}")



# ----------------------------------------------------------------------
# period_router/seating.py
# ----------------------------------------------------------------------

"""Seatings: where to put a period's qubits so every interacting pair are neighbours.

In graph terms a seating is a subgraph monomorphism from the period's
interaction graph into the chip. We find them with our own backtracking search
rather than networkx's VF2, because ours has a step budget: VF2 can take
exponential time to prove that a large pattern does NOT fit, and cannot be
interrupted.

When choosing among seatings, the cost of a seating is
    (total hops the period's qubits move from where they sit now)
  + UPCOMING_WEIGHT x (how far apart the next gates' pairs would end up)
The second term is the look-ahead across periods: prefer seatings that are
cheap to leave, not just cheap to reach.
"""




FIT_BUDGET = 20_000  # steps to spend proving a seating exists
CLOSEST_BUDGET = 2_000  # steps to spend improving on the first seating found
UPCOMING_WEIGHT = 1.0  # one hop of future distance counts the same as one hop moved now


def search_order(pattern: nx.Graph) -> list[int]:
    """Breadth-first order, so every qubit after the first in its group has a
    partner already seated. That caps its options at that chair's neighbours."""
    order = []
    components = sorted(nx.connected_components(pattern), key=lambda c: (-len(c), min(c)))
    for component in components:
        root = max(sorted(component), key=pattern.degree)
        order.append(root)
        order.extend(child for _, child in nx.bfs_edges(pattern, root))
    return order


def search_seating(
    pattern: nx.Graph,
    chip: Chip,
    reference: dict[int, int] | None = None,
    upcoming: list[tuple[int, int, float]] = (),
    budget: int = FIT_BUDGET,
) -> dict[int, int] | None:
    """Find a seating (logical -> physical) for every node of `pattern`.

    reference=None: return the first seating found.
    reference given: return the cheapest seating found (see module docstring).
    upcoming: (a, b, weight) pairs for the gates after this period.
    Returns None if the budget runs out before any seating is found.
    """
    order = search_order(pattern)
    dist, neighbors = chip.dist, chip.neighbors
    partners = {node: list(pattern.neighbors(node)) for node in order}
    need = {node: len(partners[node]) for node in order}
    all_chairs = frozenset(neighbors)
    seat: dict[int, int] = {}
    used: set[int] = set()
    best_cost = math.inf
    best_seat: dict[int, int] | None = None
    steps = 0

    pairs_of = defaultdict(list)  # node -> [(other qubit, weight)]
    for a, b, weight in upcoming:
        if a in pattern:
            pairs_of[a].append((b, weight))
        if b in pattern:
            pairs_of[b].append((a, weight))

    def added_cost(node: int, chair: int) -> float:
        """Cost of seating `node` on `chair`, given who is seated already."""
        if reference is None:
            return 0.0
        total = float(dist[reference[node]][chair])
        for other, weight in pairs_of[node]:
            if other in seat:  # both in the period: count once, when the second is seated
                total += UPCOMING_WEIGHT * weight * (dist[chair][seat[other]] - 1)
            elif other not in pattern and other in reference:  # other stays where it is
                total += UPCOMING_WEIGHT * weight * max(0, dist[chair][reference[other]] - 1)
        return total

    def candidates(node: int) -> list[tuple[float, int]]:
        seated_partners = [seat[n] for n in partners[node] if n in seat]
        if seated_partners:
            options = neighbors[seated_partners[0]]
            for chair in seated_partners[1:]:
                options = options & neighbors[chair]
        else:
            options = all_chairs
        scored = [(added_cost(node, c), c) for c in options if c not in used and len(neighbors[c]) >= need[node]]
        return sorted(scored)

    def extend(k: int, cost: float) -> bool:
        """Returns True when the search should stop."""
        nonlocal best_cost, best_seat, steps
        if k == len(order):
            best_cost, best_seat = cost, dict(seat)
            return reference is None or cost == 0  # nothing can beat zero
        node = order[k]
        for extra, chair in candidates(node):
            new_cost = cost + extra
            if new_cost >= best_cost:
                continue
            steps += 1
            if steps > budget:
                return True
            seat[node] = chair
            used.add(chair)
            stop = extend(k + 1, new_cost)
            del seat[node]
            used.discard(chair)
            if stop:
                return True
        return False

    extend(0, 0.0)
    return best_seat


def closest_seating(
    pattern: nx.Graph,
    reference: dict[int, int],
    chip: Chip,
    upcoming: list[tuple[int, int, float]] = (),
) -> dict[int, int]:
    """The cheapest seating found (see module docstring). The pattern must be one
    that fit.fits() accepted, so a seating is known to exist."""
    seat = search_seating(pattern, chip, reference, upcoming, CLOSEST_BUDGET) or search_seating(pattern, chip)
    if seat is None:
        raise ValueError("pattern has no seating; check fits() first")
    return seat



# ----------------------------------------------------------------------
# period_router/fit.py
# ----------------------------------------------------------------------

"""Does a stretch of the program fit on the chip with zero SWAPs?

"Fits" means: there is a seating where every interacting pair sits on
neighbouring physical qubits. In graph terms, the interaction graph is
subgraph-monomorphic to the chip. Monomorphic, not isomorphic: two qubits that
never interact are allowed to sit next to each other.
"""




def cannot_fit(pattern: nx.Graph, chip: Chip) -> bool:
    """Instant proofs that a pattern cannot fit. False means 'not ruled out'."""
    if pattern.number_of_edges() == 0:
        return False
    if pattern.number_of_nodes() > chip.graph.number_of_nodes():
        return True
    if max(degree for _, degree in pattern.degree()) > chip.max_degree:
        return True  # someone has more partners than any chair has neighbours
    if chip.bipartite and not nx.is_bipartite(pattern):
        return True  # an odd loop cannot be drawn on a chip with only even loops
    if nx.girth(pattern) < chip.girth:
        return True  # a loop shorter than the chip's shortest loop
    return False


def fits(pattern: nx.Graph, chip: Chip) -> bool:
    """True only if a seating was actually found. If the search budget runs out,
    the answer is False: the period just ends earlier, which is always safe."""
    if pattern.number_of_edges() == 0:
        return True
    if cannot_fit(pattern, chip):
        return False
    return search_seating(pattern, chip) is not None


def longest_fitting_end(program: list[tuple], start: int, chip: Chip) -> int:
    """Largest end such that program[start:end] fits. Always at least start + 1.

    Binary search works because fitting is monotone: if a stretch fits, every
    shorter stretch from the same start fits too. It only ever moves `lo` onto
    an end that fits(), so the answer is always a stretch that really fits.
    """
    lo, hi = start + 1, len(program)  # program[start:lo] is a single op, which always fits
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if fits(interaction_graph(program[start:mid]), chip):
            lo = mid
        else:
            hi = mid - 1
    return lo



# ----------------------------------------------------------------------
# period_router/token_swap.py
# ----------------------------------------------------------------------

"""Reshuffle: neighbour SWAPs that move some qubits onto target chairs.

Qubits without a target, and empty chairs, can end up anywhere.

Phase 1 is greedy: keep making the SWAP that brings target-holders closest to
their targets in total, while some SWAP still helps. It is short but can get
stuck, e.g. when a qubit must pass through one that is already in place.

Phase 2 always finishes: fill the leaves of a spanning tree one at a time, then
lock them. It is longer, so it only runs when phase 1 gets stuck. Measured: the
reshuffles the period router actually keeps are almost all small (0-3 SWAPs),
so a cleverer phase 2 would barely change the score.
"""




def token_swap(layout: Layout, target: dict[int, int], chip: Chip) -> list[tuple[int, int]]:
    """Move every logical qubit in `target` onto its chair. Mutates `layout`
    and returns the SWAPs made, in order."""
    swaps: list[tuple[int, int]] = []
    dist = chip.dist

    def swap(p: int, q: int) -> None:
        if layout.occupant.get(p) is None and layout.occupant.get(q) is None:
            return  # swapping two empty chairs changes nothing
        layout.swap(p, q)
        swaps.append((p, q))

    def gain(p: int, q: int) -> int:
        a, b = layout.occupant.get(p), layout.occupant.get(q)
        total = 0
        if a in target:
            total += dist[p][target[a]] - dist[q][target[a]]
        if b in target:
            total += dist[q][target[b]] - dist[p][target[b]]
        return total

    # Phase 1: greedy
    while True:
        best_edge, best_gain = None, 0
        for p, q in chip.graph.edges:
            g = gain(p, q)
            if g > best_gain:
                best_edge, best_gain = (p, q), g
        if best_edge is None:
            break
        swap(*best_edge)

    if all(layout.where[logical] == chair for logical, chair in target.items()):
        return swaps

    # Phase 2: spanning-tree leaf filling
    remaining = nx.Graph(nx.bfs_tree(chip.graph, chip.center))
    wanted_at = {chair: logical for logical, chair in target.items()}
    while remaining.number_of_nodes():
        leaf = min(v for v in remaining if remaining.degree(v) <= 1)
        wanted = wanted_at.get(leaf)
        if wanted is not None:
            source = layout.where[wanted]
        else:  # the leaf needs anything that has no target: an empty chair or a free qubit
            free = [v for v in remaining if layout.occupant.get(v) not in target]
            lengths = nx.single_source_shortest_path_length(remaining, leaf)
            source = min(free, key=lambda v: (lengths[v], v))
        path = nx.shortest_path(remaining, source, leaf)
        for p, q in zip(path, path[1:]):
            swap(p, q)
        remaining.remove_node(leaf)
    return swaps



# ----------------------------------------------------------------------
# period_router/lookahead.py
# ----------------------------------------------------------------------

"""Gate-by-gate router with lookahead: the fallback for stretches that don't fit.

For a gate whose qubits are apart, every SWAP it makes moves one of them one
hop closer to the other, so routing a gate always ends. When several SWAPs do
that, it picks the one that leaves the next few gates closest together.
"""


LOOKAHEAD = 20  # how many upcoming gates to consider
DECAY = 0.8  # each later gate counts this much less than the one before


def upcoming_cost(layout: Layout, upcoming: list[tuple[int, int, float]], chip: Chip) -> float:
    return sum(weight * chip.dist[layout.where[a]][layout.where[b]] for a, b, weight in upcoming)


def route_gate(layout: Layout, a: int, b: int, upcoming: list[tuple[int, int, float]], chip: Chip) -> list[tuple[int, int]]:
    """SWAPs that make logical a and b neighbours. Mutates `layout`."""
    swaps = []
    dist = chip.dist
    while dist[layout.where[a]][layout.where[b]] > 1:
        pa, pb = layout.where[a], layout.where[b]
        gap = dist[pa][pb]
        options = [
            (mover, step)
            for mover, other in ((pa, pb), (pb, pa))
            for step in sorted(chip.graph.neighbors(mover))
            if dist[step][other] == gap - 1
        ]

        def score(option: tuple[int, int]) -> tuple[float, tuple[int, int]]:
            layout.swap(*option)
            value = upcoming_cost(layout, upcoming, chip)
            layout.swap(*option)  # undo
            return value, option

        best = min(options, key=score)
        layout.swap(*best)
        swaps.append(best)
    return swaps


def route_span(program: list[tuple], start: int, end: int, layout: Layout, chip: Chip) -> list[tuple]:
    """Route program[start:end] gate by gate. Looks past `end` for lookahead. Mutates `layout`."""
    routed = []
    for index in range(start, end):
        op = program[index]
        if op[0] == "2Q":
            upcoming = upcoming_pairs(program, index + 1, LOOKAHEAD, DECAY)
            for p, q in route_gate(layout, op[1], op[2], upcoming, chip):
                routed.append(("SWAP", p, q))
        routed.append(layout.emit(op))
    return routed


def route_lookahead(program: list[tuple], placement: dict[int, int], chip: Chip) -> list[tuple]:
    """The whole program, gate by gate."""
    return route_span(program, 0, len(program), Layout(placement), chip)



# ----------------------------------------------------------------------
# period_router/initial.py
# ----------------------------------------------------------------------

"""Starting seating: the first period seated near the chip's centre, then
everyone else placed next to the partners they talk to most."""



def initial_placement(program: list[tuple], chip: Chip) -> dict[int, int]:
    qubits = logical_qubits(program)
    if len(qubits) > chip.graph.number_of_nodes():
        raise ValueError(f"program uses {len(qubits)} qubits but the chip has {chip.graph.number_of_nodes()}")
    if not program:
        return {}

    first_end = longest_fitting_end(program, 0, chip)
    first_period = interaction_graph(program[:first_end])
    upcoming = upcoming_pairs(program, first_end, LOOKAHEAD, DECAY)
    placement = closest_seating(first_period, {q: chip.center for q in first_period}, chip, upcoming)

    partners = partner_counts(program)
    dist = chip.dist
    for qubit in first_appearance(program):
        if qubit in placement:
            continue
        taken = set(placement.values())
        free = [p for p in chip.graph.nodes if p not in taken]

        def pull(chair: int) -> tuple:
            to_partners = sum(
                count * dist[chair][placement[partner]]
                for partner, count in partners[qubit].items()
                if partner in placement
            )
            return to_partners, dist[chip.center][chair], chair

        placement[qubit] = min(free, key=pull)
    return placement


def label_order_placement(program: list[tuple], chip: Chip) -> dict[int, int]:
    """Logical qubits in label order onto physical qubits in label order.

    Naive, but when a program's labels follow the chip's wiring (e.g. qubit k
    talks to k+1 on a ring) it is already near-perfect, so it is worth trying.
    """
    return dict(zip(logical_qubits(program), sorted(chip.graph.nodes)))



# ----------------------------------------------------------------------
# period_router/periods.py
# ----------------------------------------------------------------------

"""The period router.

Cut the program into periods: the longest stretches that fit with zero SWAPs.
For each period, compare two ways of handling it and keep the cheaper:
  reseat - reshuffle to the closest seating where the whole period fits, or
  route  - leave the seating alone and route the period gate by gate.
"Cheaper" is the real score (SWAPs + 0.5 x depth) of everything emitted so far.
"""




def reseat_span(program: list[tuple], start: int, end: int, layout: Layout, chip: Chip) -> list[tuple]:
    """Reshuffle to the closest seating that fits program[start:end], then emit it. Mutates `layout`."""
    pattern = interaction_graph(program[start:end])
    routed = []
    if pattern.number_of_edges():
        upcoming = upcoming_pairs(program, end, LOOKAHEAD, DECAY)
        target = closest_seating(pattern, layout.where, chip, upcoming)
        routed = [("SWAP", p, q) for p, q in token_swap(layout, target, chip)]
    routed.extend(layout.emit(op) for op in program[start:end])
    return routed


def route_periods(program: list[tuple], placement: dict[int, int], chip: Chip, stats: dict | None = None) -> list[tuple]:
    layout = Layout(placement)
    routed: list[tuple] = []
    start = 0
    while start < len(program):
        end = longest_fitting_end(program, start, chip)

        reseat_layout = layout.copy()
        reseated = reseat_span(program, start, end, reseat_layout, chip)
        route_layout = layout.copy()
        gate_by_gate = route_span(program, start, end, route_layout, chip)

        if cost(routed + reseated) <= cost(routed + gate_by_gate):
            routed += reseated
            layout = reseat_layout
            choice = "reseat"
        else:
            routed += gate_by_gate
            layout = route_layout
            choice = "route"

        if stats is not None:
            stats.setdefault("periods", []).append((end - start, choice))
        start = end
    return routed



# ----------------------------------------------------------------------
# period_router/solve.py
# ----------------------------------------------------------------------

"""solve(): try every router from every starting seating, keep the best valid result.

Starting seatings:
  1. initial_placement      - first period near the centre, the rest by partners
  2. label_order_placement  - qubit k on chair k (good when labels follow the wiring)
Each is then refined with the forward-backward trick (from SABRE): route the
program forwards, then backwards from where everyone ended up; where they end up
after that is a seating shaped by the whole program. Refining continues while it
lowers the score, up to MAX_REFINE_ROUNDS.
"""




ROUTERS = (route_periods, route_lookahead)
MAX_REFINE_ROUNDS = 5


def final_placement(placement: dict[int, int], routed: list[tuple]) -> dict[int, int]:
    """Where every logical qubit sits after all the SWAPs in `routed`."""
    layout = Layout(placement)
    for op in routed:
        if op[0] == "SWAP":
            layout.swap(op[1], op[2])
    return layout.where


def forward_backward(program: list[tuple], placement: dict[int, int], chip: Chip) -> dict[int, int]:
    after_forward = final_placement(placement, route_periods(program, placement, chip))
    return final_placement(after_forward, route_periods(program[::-1], after_forward, chip))


def solve(program: list[tuple], hardware_graph: nx.Graph) -> tuple[dict[int, int], list[tuple]]:
    """
    Args:
        program: list of tuples
            ("2Q", i, j) = two-qubit gate between logical qubits i and j
            ("1Q", i)    = single-qubit gate on logical qubit i
        hardware_graph: networkx.Graph
            Nodes are physical qubit indices, edges are connections

    Returns:
        initial_placement: dict
            Maps logical qubit index → physical qubit index
            e.g. {0: 5, 1: 6, 2: 9, 3: 10}
        routed_program: list of tuples
            Same format as input, but on PHYSICAL qubits,
            with ("SWAP", p, q) operations inserted as needed.
            Every ("2Q", p, q) must have (p,q) as an edge in hardware_graph.
    """
    chip = make_chip(hardware_graph)
    best: tuple[dict[int, int], list[tuple]] | None = None

    def best_from(placement: dict[int, int]) -> float:
        """Route from `placement` with every router; keep the overall best. Returns this seed's best cost."""
        nonlocal best
        seed_best = float("inf")
        for router in ROUTERS:
            routed = router(program, placement, chip)
            if not validate(program, hardware_graph, placement, routed):
                raise RuntimeError(f"{router.__name__} produced an invalid program")  # a bug
            score = cost(routed)
            seed_best = min(seed_best, score)
            if best is None or score < cost(best[1]):
                best = (dict(placement), routed)
        return seed_best

    for placement in (initial_placement(program, chip), label_order_placement(program, chip)):
        score = best_from(placement)
        for _ in range(MAX_REFINE_ROUNDS):
            placement = forward_backward(program, placement, chip)
            refined = best_from(placement)
            if refined >= score:
                break
            score = refined
    return best
